### ISSUE TITLE
Generators: Add `testcase: count: X` for multiple testcase copies

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#271]
Currently we do
```yaml
- random: gen.py {seed:1}
- random: gen.py {seed:2}
- random: gen.py {seed:3}
```
which would be nice to replace with
```yaml
- random:
    input: gen.py {seed}
    count: 3
```

(And maybe `input:` should be renamed to `gen:`?)

**Comment by mpsijm** [comment]
Duplicate of #135 and #162? (the fact that you've opened the same issue three times, probably means we should implement it :joy:)

Also relates to #272 (/ #220), for the naming of the `input:`/`gen:` key.

**Comment by RagnarGrootKoerkamp** [comment]
Hmm; the problem with 'inline' numbering is that that wouldn't work if testcases aren't already numbered in the first place. For named cases you'd have to do `random-1`, `random-2`, or so.

**Comment by thorehusfeldt** [comment]
This is of course super useful for other generators than random ones. 

Assume `trees.py --i` is a generator that produces all nonisomorphic trees on 7 vertices (indexed by `k`), I would love to do

```yaml
- small:
    input: trees.py --k {seed}
    count: {2,4,5-12, 14}
```

instead of
```yaml
- small trees.py --k 1
- small trees.py --k 2
- small trees.py --k 3
...
```

**Comment by RagnarGrootKoerkamp** [comment]
Ohh, interesting idea.

**Some context**
Currently we allow `{seed}` and `{seed:<any kind of salt>}`, and the entire thing is replace by an integer hash of *the entire* generate command. (This way, `gen.py {seed} 1` and `gen.py {seed} 2` have distinct seeds, and `gen.py {seed:1}` and `gen.py {seed:2}` also have distinct seeds.
This also means that `{seed}` is *not* a small incremental int typically. It's supposed to be used has seed a random number generator, but I still think it's good if `{seed}` is always pseudo-random, never `1, 2, 3, ...`.

**Variables**
The above means that your example isn't the intended way of using `{seed}`. But I think we can do something cleaner:
```yaml
- testcase:
    input: gen.py -n {n}
    n: [1,2,3, 10, 100, 1000]
```
Note that the value of `n` here is simply a list, and we generate one testcase for each element of the list.

Or maybe we should separate the variable `n` into a separate scope? (I don't think it's really needed though.)
```yaml
- testcase:
    input: gen.py -n {n}
    vars:
      n: [1,2,3, 10, 100, 1000]
```

**Expressions**
Since we already use python syntax, we could also allow eg `input: gen.py -n {2**i}`, but I don't think this is really necessary.

**Multiple variables**
For multiple variables, we have to figure out how to make combinations:
```yaml
- testcase:
    input: gen.py -n {n} -k {k}
    n: [1,2,3, 10, 100, 1000]
    k: [2,3,4,5,6,7]
```
This could mean either:
a) cartesian product of the two lists, creating 6*6 = 36 testcases
b) 'zipped' parameters, creating testcases with `(n,k) in [(1,2), (2,3), (3, 4), (10, 5), (100, 6), (1000, 7)]`.
My initial preference is zipping: cartesian products quickly explode the number of testcases, and in practice I often want two parameters to grow in step with each other (e.g. the number of vertices and edges of a graph -- cartesian product wouldn't make sense there). This would imply an assertion that all lists have the same length.

**Seeds**
Back to the original question, we could reuse the variable syntax and do
```yaml
- testcase:
    input: gen.py {seed}
    seed: [1, 2, 3]
```
this would then mean `{seed}` is replaced by `1`, `2`, and `3`. I think I can live with this since ideally `{seed}` should be used to seed an RNG. Alternatively we could special case this to mean that `{seed}` is replaced by the hash of `gen.py {seed:1}` and so on, which is backwards compatible with how we already do thing.

**Counting the number of testcases**
I'd say that any 'unrecognised key' (ie not `input solution visualizer in ans desc hint ...`) is automatically assumed to be a variable and required to have `list` type. All these lists must have the same length (assuming we zip them), and that length is used as the count of testcases for this rule.

**Comment by mpsijm** [comment]
My two cents:
- I agree that `{seed}` should always be pseudo-random.
- I prefer a separate key for all variables (or as you called it [here](https://github.com/RagnarGrootKoerkamp/BAPCtools/issues/271#issuecomment-1611362832), a "separate scope").
- About the zipping, I think [your last comment](https://github.com/RagnarGrootKoerkamp/BAPCtools/issues/271#issuecomment-1611406572) would work well for me. I assume you can also write this as follows?
```yaml
- testcase:
    input: gen.py -n {n} -k {k}
    vars:
      - {n: 1, k: 1}
      - {n: 2, k: 2}
      - ...
```
  Or possibly even like this, if you want to be very verbose?

```yaml
- testcase:
    input: gen.py -n {n} -k {k}
    vars:
      - n: 1
        k: 1
      - n: 2
        k: 2
      - ...
```

And then a final question: how does `vars` combine with `count`? My intuition would say that, for every (tuple of) value(s), the test case would be duplicated `count` times. So in the following example, you would get six test cases:
```
- testcase:
    input: gen.py -n {n} -k {k} -seed {seed}
    vars: [{n: 1, k: 1}, {n: 2, k: 2}]
    count: 3
```

Now that I think of it, `count` should probably be ignored (or even better, rejected) when the `input` does not contain `{seed}`.

**Comment by RagnarGrootKoerkamp** [comment]
- Yes, `count:` should require `{seed}`.
- I'm really not a fan of the dictionary syntax `vars: [{n:1}, {n:2}, {n:3}, ..]` is so verbose compared to `vars: n: [1,2,3, ...]`, that just copying the entire line modifying the two numbers is simpler. I think for multiple vars something like `vars: [(1,2), (2, 4), (3, 8), ...]` would be cool.

**Comment by mpsijm** [comment]
> I think for multiple vars something like `vars: [(1,2), (2, 4), (3, 8), ...]`

Yes, that's nice! In that case, do we need to name the variables? We could also go for something like: 

```yaml
- testcase:
    input: gen.py -n {} -k {}
    vars: [(1, 2), (2, 4), ...]
```

Note that I usually write my Python generators with positional arguments, so that would look something like `input: gen.py {} {}`. I guess that's fine, if I put a comment documenting which variable is which :stuck_out_tongue:
