### ISSUE TITLE
[gen]: CUE schema `[string]` template fails to match empty string

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#279]
Low priority, but in the CUE schema, the expression 
```json
data_dict: [string]: directory | generator | null
```
fails to mach the first entry in
```yaml
   data:
          # 1.in
          - "": stdout.py empty
          # 2-a.in
          - a: stdout.py empty
```
i.e., the key `""`. 

The error is
```bash
> cue vet ../doc/generators.yaml generators_yaml_schema.cue -d 'Generators'
optional fields not allowed in graph mode:
    ../doc/generators.yaml:177:14
```
I’m not sure why this happens, maybe the implementation of the `[string]` template is wrong.

In particular, our current CUE schema fails to validate our model `generators.yaml` document.
