### ISSUE TITLE
data/bad: renaming and generation

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#303]
TODOs for invalid inputs:

1. Make BAPCtools recognise `data/invalid_inputs`, continue supporting `data/bad` but with a warning
2. Move the files currently created by `bt new_problem` in `data/bad` to the generator. This requires changing the standard skeleton, and is not trivial:
```yaml
'empty':
  in: '' # BAPCtools forbids this (“Hardcoded .in data may not be empty!”)
'newline':
  in: "\n" # this is fine with those quotes
'random_printable': 
  in: YVRtr&*teTsRjs8ZC2%kN*T63V@jJq!d # also fine
'unicode':
  in: "¯\\_(ツ)_/¯" # fine with the extra backslash and those quotes
'not_printable':
  in: ... # now what? I’m stumped
```
What is worrisome is that parts of the toolchain (in particular, python’s YAML parser) may choke on the non-printable unicode shenanigans before it ever gets to write the `.in` file.

**Comment by mzuenni** [comment]
It is probably easier to add a generator which produces these
```
#!/usr/bin/env python3

import sys

strings = {
	'empty': b'',
	'newline' : b'\n',
	'random_printable' : b'YVRtr&*teTsRjs8ZC2%kN*T63V@jJq!d\n',
	'unicode' : bytes('¯\\_(ツ)_/¯\n', 'utf-8'),
	'not_printable1' : b'\x7f\n',
	'not_printable2' : b'\xe2\x82\xac\n'
}

sys.stdout.buffer.write(strings[sys.argv[1]])

```

**Comment by thorehusfeldt** [comment]
That would work, but then we’re back at a mandatory `stdout.py`-like generator that practically always has to be there, and a lot of redundancy. This seems like a step backwards.

I’d prefer to either have some good, explicit `invalid_inputs` in the skeleton-provided generator _or_ move this to the behind-the-curtains sanity check.

I _think_ something like the following works for me:

```yaml
data:
  bad:
    data:
      'newline':
        in: "\n"
      'random_printable': 
        in: YVRtr&*teTsRjs8ZC2%kN*T63V@jJq!d
      'unicode':
        in: "¯\\_(ツ)_/¯"
      'not_printable1': 
        in: "\x7f"
      'not_printable2':
        in: "\xe2\x82\xac"
      'bismillah':
        in: "﷽"
```
But the empty testcase `""` needs special attention from BAPCtool here:

https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/9cc3a8511e74984328fdf0f6474bb34f4e212590/bin/generate.py#L768

1 The error message should say _must_ <s>may</s>.
2. The check should not run in `invalid_input/*`.
