### ISSUE TITLE
Make auto-numbering of `bt generate` consistent with DOMjudge numbering

### ISSUE THREAD

**Issue by mpsijm** [RagnarGrootKoerkamp/BAPCtools#325]
We should auto-number samples so that DOMjudge's internal numbering is the same as ours (so if there are two samples, `3.in` would be the first secret case).

When fixing this, please double-check that samples with leading zeroes are correctly picked up by the PDF. We've had some instances where we a file like `001.interaction` is not picked up by the PDF.

**Comment by mzuenni** [comment]
Do we want to zero-pad the samples like the secret cases or it is sufficient to have secret cases start at |samples|+1? And what is the expected behaviour if there are other folders in `/data`?

**Comment by thorehusfeldt** [comment]
For reference: [Summer 2023 discussion of test case numbering by `bt generate`.](https://github.com/RagnarGrootKoerkamp/BAPCtools/pull/274)

**Comment by thorehusfeldt** [comment]
The only way I can see this work with the current decisions about automatic numbering is to introduce a setting for it, maybe as part of `#testgroup/#config` in the schema:
```yaml
data:
  secret:
    numbering:
      start: 3
      padding: False
    data:
        foo: my_generator 344
```
We’d probably want to invent reserved values for `start` like `start: sibling`.

This seems to require a lot of thought to do well. (An altenative is to have a single rule that kicks in exactly if the directory structure is `data/secret/list_of_cases` and `data/sample/list_of_cases` and nothing else.

**Comment by RagnarGrootKoerkamp** [comment]
@thorehusfeldt Currently auto-numbering is implemented as follows:
1. Collect *all* auto-numbered cases in `generators.yaml`.
2. Sort them lexicographically.
3. Number them 1 to n.
4. Left pad all of them with zeros.

So this already works for samples. I think all that's needed is to change the template from
```yaml
samples:
  data:
    1: ...
    2: ...
```
to
```yaml
samples:
  data:
    - '': ...
    - '': ...
```
