### ISSUE TITLE
Report test cases with duplicate contents

### ISSUE THREAD

**Issue by mpsijm** [RagnarGrootKoerkamp/BAPCtools#414]
On BAPC preliminaries problem Lawful Limits, Kattis' Problemtools' `verifyproblem` reports:

```
Identical input files: '['data/secret/4-large/52-large-grid-3.in', 'data/secret/4-large/51-large-grid-2.in', 'data/secret/4-large/50-large-grid-1.in']'
```

The corresponding generate-config is:
```yaml
            - large-grid:
                generate: grid.py 300 300
                count: 3
```
So it was literally (probably unintentionally) configured to generate three duplicate test cases.

So either we should
1. warn for `count:` without `{seed}`, or
2. we should fully check for duplicate tests (probably aided by hash collision checking to speed things up)

Or maybe both. What do you think?
